[package]
name = "lists"
version = "0.1.0"
authors = ["Amitay <amitaybremer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
testdrop = "0.1.2"
